name: Java CI/CD with Maven and Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Ensure this secret is defined in the repository settings
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Ensure this secret is defined in the repository settings
    
    - name: Build and push Docker images
      env:
        REPOSITORY_PREFIX: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: |
        echo "Docker Hub Username: ${REPOSITORY_PREFIX}"  # Debug line, remove after testing
        mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${REPOSITORY_PREFIX}
        ./scripts/pushImages.sh
    
    # - name: Deploy to Kubernetes
    #   run: |
    #     # Add your Kubernetes deployment commands here
    #     # For example:
    #     # kubectl apply -f k8s/deployment.yaml
    #     # kubectl apply -f k8s/service.yaml